config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sabakatus#index"
  resources :users, only:[:show]
  resources :profiles, only:[:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
self.data = [
  { id: 1, name: '---' },
  { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
  { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
  { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
  { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
  { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
  { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
  { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
  { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
  { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
  { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
  { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
  { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
  { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
  { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
  { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
  { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
]

include ActiveHash::Associations
has_on :Profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  has_one_attached :image
  belongs_to :usre

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  #has_many :rooms, through: room_users
  has_many :messages 
  has_many :Photos
  has_one :profile

  with_options presence: true do
    validates :name
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :email, :password])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to root_path
  end

  private

  def profile_params
    params.require(:profile).permit(:image, :field, :history, :gun, ).merge(user_id: current_user.id)
  end
end

app/controllers/sabakatus_controller.rb
class SabakatusController < ApplicationController
  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sabakatu_helper.rb
module SabakatuHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SABAKATU</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/profiles/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :hoge, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :hoge, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :hoge, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :hoge, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/profiles/new.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('sainup.png' , size: '150x150') %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">プロフィール情報を入力</h2>
    <%= form_with(model: @profile, local: true) do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# アイコン画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        アイコン画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /アイコン画像 %>
    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">
        活動地域
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :field, class:"items-text", id:"item-name", placeholder:"フィールド名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品の詳細 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        フィールド
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :field, class:"items-text", id:"item-name", placeholder:"フィールド名（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        サバゲー歴
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :history, class:"items-text", id:"item-name", placeholder:"サバゲー歴（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        愛銃
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :gun, class:"items-text", id:"item-name", placeholder:"愛銃名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名と商品説明 %>

    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%=f.submit "登録する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%= link_to image_tag('sainup.png' , size: '100x100')  %>
    <p class="inc">
      ©︎SABAKATU
    </p>
  </footer>
</div>

app/views/sabakatu/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「SABAKATU」帯部分 %>
  <div class='title-contents'>
    <h1 class='service-title'>
      サバゲー総合アプリサイト
    </h1>
    <p class='service-subtitle'>
      SABAKATU
    </p>
    <p class='service-explain'>
      非日常の体験をしよう！
    </p>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      content
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "field.jpeg", class:"list-pict" %>
        <p class='reason-list-text'>
          フィールド
        </p>
      </li>
      <li class='list'>
        <%= image_tag "shop.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          ショップ
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "Photo.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          ピクチャ
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "community.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          コミュ二ティ
        </h3>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      サバゲー初心者ガイド
    </h2>
    <p class='ad-explain'>
      『サバゲーをしてみたいげど何が必要なんだろう』
    </p>
    <p class='ad-explain'>
      これさえあれば、すぐにサバゲーを始めれます！
    </p>
    <p class='ad-explain'>
      気軽にサバゲーを体験してみよう！
    </p>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      サバゲーに必要なモノ
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "goggle.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          ゴーグル
        </h3>
        <p class='feature-list-description'>
          失明の危険があるので、目は絶対に保護しよう
        </p>
      </li>
      <li class='list'>
        <%= image_tag "gan.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          エアーガン、電動ガン
        </h3>
        <p class='feature-list-description'>
          自分の好きなモノで遊ぼう（レンタルも有ります）
        </p>
      </li>
      <li class='list'>
        <%= image_tag "huku.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          衣服
        </h3>
        <p class='feature-list-description'>
          動きやすい服を選ぼう（ジャージでもOK)
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップピクチャー</h2>
    <div class="subtitle" >
      最新投稿写真
    </div>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <li class='list'>
        <%= link_to "#" do %>
        <div class='item-img-content'>
          <%= image_tag "imag.jpeg", class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= "投稿者名" %>
          </h3>
          <div class='item-price'>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to('#', class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/sabakatus/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「SABAKATU」帯部分 %>
  <div class='title-contents'>
    <h1 class='service-title'>
      サバゲー総合アプリサイト
    </h1>
    <p class='service-subtitle'>
      SABAKATU
    </p>
    <p class='service-explain'>
      非日常の体験をしよう！
    </p>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# sa部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      content
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "field.jpeg", class:"list-pict" %>
        <p class='reason-list-text'>
          フィールド
        </p>
      </li>
      <li class='list'>
        <%= image_tag "shop.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          ショップ
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "Photo.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          ピクチャ
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "community.jpeg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          コミュ二ティ
        </h3>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      サバゲー初心者ガイド
    </h2>
    <p class='ad-explain'>
      『サバゲーをしてみたいげど何が必要なんだろう』
    </p>
    <p class='ad-explain'>
      これさえあれば、すぐにサバゲーを始めれます！
    </p>
    <p class='ad-explain'>
      気軽にサバゲーを体験してみよう！
    </p>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      サバゲーに必要なモノ
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "goggle.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          ゴーグル
        </h3>
        <p class='feature-list-description'>
          失明の危険があるので、<br>目は絶対に保護しよう
        </p>
      </li>
      <li class='list'>
        <%= image_tag "gan.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          エアーガン、電動ガン
        </h3>
        <p class='feature-list-description'>
          自分の好きなモノで遊ぼう<br>（レンタルも有ります）
        </p>
      </li>
      <li class='list'>
        <%= image_tag "huku.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          衣服
        </h3>
        <p class='feature-list-description'>
          動きやすい服を選ぼう<br>（ジャージでもOK)
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップピクチャー</h2>
    <div class="subtitle" >
      最新投稿写真
    </div>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <li class='list'>
        <%= link_to "#" do %>
        <div class='item-img-content'>
          <%= image_tag "imag.jpeg", class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= "投稿者名" %>
          </h3>
          <div class='item-price'>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to('#', class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SABAKATUについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("sabakatu-rogo.png", class:"logo-white"), "#" %>
  <p>© SABAKATU</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header' >
  <div class='search-bar-contents'>
    <%= link_to image_tag("sabakatu-rogo.png", class:"hitogata-icon"), "" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"  %></li>
      <% else%>
        <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>

    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <%= image_tag "sainup.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("rogin.png", class:"second-logo") %>
</header>

app/views/users/show.html.erb
<%# 商品の概要 %>
<div class="-show">
  <div class="item-box">
    <h2 class="name">
      <%= @user.nickname %>
    </h2>
    <div class="item-img-content">
      <%= image_tag "ikon.png" ,class:"item-box-img" %>
      <%# <%= image_tag profiles_url.png.variant(resize: '500x500'), class: 'profiles-image' if profiles_url.image.attached? %> %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ニックネーム</th>
          <td class="detail-value"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">活動地域</th>
          <td class="detail-value"><%= "活動地域" %></td>
        </tr>
        <tr>
          <th class="detail-item">フィールド</th>
          <td class="detail-value"><%= "フィールド" %></td>
        </tr>
        <tr>
          <th class="detail-item">サバゲー歴</th>
          <td class="detail-value"><%= "サバゲー歴" %></td>
        </tr>
        <tr>
          <th class="detail-item">愛銃</th>
          <td class="detail-value"><%= "愛銃" %></td>
        </tr>
      </tbody>
    </table>
    <div class="sabage-btn">
      <% if current_user.id == current_user.id %>
        <%= link_to "登録", new_profile_path, method: :get, class: "item-new-btn" %>
      <% else %>
        <%= link_to "編集", edit_user_path, method: :get, class: "item-red-btn" %>
        <%= link_to "削除", "#", method: :delete, class:"item-destroy" %>
      <% end%>
    </div>
  </div>
</div>